### ISSUE TITLE
Decide on intermediate data format

### ISSUE THREAD

**Issue by axdanbol** [cns-iu/map4sci#4]
Currently the dot file format is mostly used for intermediate data storage but it can be a bit of a pain to work with.
Suggestions:
- pickle (python object serialization)
- json

**Comment by bherr2** [comment]
pickle may be a good solution. networkx has functions for saving graphs to/from pickles. See <https://networkx.org/documentation/stable//reference/readwrite/gpickle.html>

**Comment by bherr2** [comment]
Another alternative is nd-json (newline-delimitted json) as this can be stream read/write. May be essential when dealing with very large graphs.

**Comment by bherr2** [comment]
Also, tippecanoe likes newline-delimitted geojson (which can enable parallel processing of the data).

**Comment by axdanbol** [comment]
For ndjson one of these library can be used to load/store data:
- https://pypi.org/project/ndjson/
- https://jsonlines.readthedocs.io/en/latest/

**Comment by bherr2** [comment]
They are both pretty equivalent, but ndjson is gpl and jsonlines is bsd, so I'd favor jsonlines unless we see it doesn't work well.

**Comment by axdanbol** [comment]
I've decided on ndjson using https://jsonlines.readthedocs.io/en/latest/ as the python library
